/**
 * AI conformance eval — 11-testing.md §3.6, pipeline of 10-ai-codegen.md §5.
 *
 * A fixed, versioned set of intent prompts is generated by a real model and
 * scored on the conformance ladder; what the suite reports is the L0/L1/L2 rate,
 * not a pass/fail. It is layer 6 of the test pyramid: non-deterministic, never a
 * CI gate (11 §4), run before releases to see whether a change to the style
 * guide or the context builder moved the rate up or down.
 *
 * The suite is deliberately dependency-free and takes the CodeFlow module as an
 * argument, so the same code runs against `src` (from Vitest) and against `dist`
 * (from `scripts/ai-eval.mjs`, under Node's type stripping). Everything that
 * touches the file system or the environment lives in the script, not here.
 *
 * Registry version: 1 — bump when the tools/functions below change, since
 * conformance rates are only comparable within one version.
 */

import type {
  createCodeFlow,
  createRegistry,
  renderDiagnosticsFeedback,
  renderSystemPrompt,
  ConformanceLevel,
  Diagnostic,
  Registry,
} from "../../src/index.js";

/** The slice of `@codeflow/core` the suite needs, from `src` or from `dist`. */
export interface CodeFlowModule {
  createRegistry: typeof createRegistry;
  createCodeFlow: typeof createCodeFlow;
  renderSystemPrompt: typeof renderSystemPrompt;
  renderDiagnosticsFeedback: typeof renderDiagnosticsFeedback;
}

// The core package is typed against ES2022 only (no DOM, no @types/node), so the
// two host APIs the suite uses are declared here rather than pulled in globally.
declare function fetch(url: string, init: RequestInit): Promise<FetchResponse>;
declare function setTimeout(handler: () => void, timeout: number): unknown;

interface RequestInit {
  method: string;
  headers: Record<string, string>;
  body: string;
}
interface FetchResponse {
  ok: boolean;
  status: number;
  text(): Promise<string>;
}

export const EVAL_REGISTRY_VERSION = 1;

/**
 * A registry deliberately wider than the canonical github/slack pair: four
 * namespaces and three library functions, so an intent has to *choose* rather
 * than use the only tool available — which is where models invent names.
 */
export function createEvalRegistry(cf: CodeFlowModule): Registry {
  const registry = cf.createRegistry();

  registry.registerTool({
    name: "github.getNewPRs",
    label: "Get New PRs",
    description: "List pull requests opened since the last run.",
    inputSchema: { repo: "string" },
    outputSchema: "PullRequest[]",
  });
  registry.registerTool({
    name: "github.getFiles",
    label: "Get PR Files",
    description: "List the files changed in a pull request.",
    inputSchema: { pr: "PullRequest" },
    outputSchema: "File[]",
  });
  registry.registerTool({
    name: "github.addComment",
    label: "Comment on PR",
    description: "Post a comment on a pull request.",
    inputSchema: { pr: "PullRequest", body: "string" },
  });
  registry.registerTool({
    name: "github.getRepoStats",
    label: "Get Repo Stats",
    description: "Commit and review statistics for a repository over the last 7 days.",
    inputSchema: { repo: "string" },
    outputSchema: "RepoStats",
  });

  registry.registerTool({
    name: "slack.send",
    label: "Send Slack Message",
    description: "Send a message to a Slack channel.",
    inputSchema: { channel: "string", message: "string" },
    outputSchema: "SlackMessage",
  });
  registry.registerTool({
    name: "slack.postThread",
    label: "Reply in Slack Thread",
    description: "Reply inside an existing Slack thread.",
    inputSchema: { channel: "string", threadId: "string", message: "string" },
  });
  registry.registerTool({
    name: "slack.getChannelActivity",
    label: "Get Channel Activity",
    description: "Message counts for a Slack channel over the last 7 days.",
    inputSchema: { channel: "string" },
    outputSchema: "ChannelActivity",
  });

  registry.registerTool({
    name: "jira.getIssue",
    label: "Get Jira Issue",
    description: "Fetch one issue by key. Throws when the issue service is unavailable.",
    inputSchema: { key: "string" },
    outputSchema: "Issue",
  });
  registry.registerTool({
    name: "jira.searchIssues",
    label: "Search Jira Issues",
    description: "Search issues with a JQL query.",
    inputSchema: { jql: "string" },
    outputSchema: "Issue[]",
  });
  registry.registerTool({
    name: "jira.createIssue",
    label: "Create Jira Issue",
    description: "Create an issue in a project.",
    inputSchema: { project: "string", summary: "string", description: "string" },
    outputSchema: "Issue",
  });
  registry.registerTool({
    name: "jira.transitionIssue",
    label: "Transition Jira Issue",
    description: "Move an issue to another status.",
    inputSchema: { key: "string", status: "string" },
  });

  registry.registerTool({
    name: "email.send",
    label: "Send Email",
    description: "Send an email to one recipient.",
    inputSchema: { to: "string", subject: "string", body: "string" },
  });
  registry.registerTool({
    name: "email.getRecentThreads",
    label: "Get Recent Email Threads",
    description: "Threads received in a mailbox over the last 7 days.",
    inputSchema: { mailbox: "string" },
    outputSchema: "EmailThread[]",
  });

  registry.registerFunction({
    name: "isAuthChange",
    label: "Is Auth Change",
    description: "True when a changed file touches authentication or permissions.",
    inputSchema: { file: "File" },
    outputSchema: "boolean",
    code: "export function isAuthChange(file: File) { return /auth|login|oauth|permission/i.test(file.path); }",
    modulePath: "@flows/lib",
  });
  registry.registerFunction({
    name: "severityOf",
    label: "Severity Of Issue",
    description: 'Classify an issue as "critical", "high" or "low".',
    inputSchema: { issue: "Issue" },
    outputSchema: "string",
    code: 'export function severityOf(issue: Issue) { return issue.priority === "P1" ? "critical" : issue.priority === "P2" ? "high" : "low"; }',
    modulePath: "@flows/lib",
  });
  registry.registerFunction({
    name: "formatDigest",
    label: "Format Digest",
    description: "Render a weekly digest from repository, issue and chat activity.",
    inputSchema: { stats: "RepoStats", issues: "Issue[]", activity: "ChannelActivity" },
    outputSchema: "string",
    code: "export function formatDigest(stats: RepoStats, issues: Issue[], activity: ChannelActivity) { return `${stats.commits} commits, ${issues.length} issues, ${activity.messages} messages`; }",
    modulePath: "@flows/lib",
  });

  return registry;
}

export interface EvalIntent {
  id: string;
  /** What the user asks for — fixed text, versioned with the suite. */
  prompt: string;
  /** MVP semantics this intent is meant to exercise (11 §3.6, 01 §2). */
  covers: string[];
}

/** Six intents covering the constructs of 01 §2 that the MVP analyzes. */
export const EVAL_INTENTS: EvalIntent[] = [
  {
    id: "security-pr-notifier",
    covers: ["for...of", "if", "library function", "tool call", "template literal"],
    prompt:
      "When the flow runs for a repository, look at the pull requests opened since the last run. " +
      "For each pull request, check the files it changes; if any of them touches authentication or " +
      "permissions, post a message to the #security Slack channel naming the pull request.",
  },
  {
    id: "bounded-retry",
    covers: ["while with bound", "try/catch", "early return"],
    prompt:
      "Fetch a Jira issue by key. The issue service is flaky, so retry up to 3 attempts before " +
      "giving up, and never loop forever. If all attempts fail, send a message to #ops saying the " +
      "issue could not be fetched and stop. Otherwise transition the issue to \"In Review\".",
  },
  {
    id: "parallel-digest",
    covers: ["Promise.all array literal", "parallel + merge", "library function"],
    prompt:
      "Build a weekly digest for a repository. Fetch three things at the same time, in parallel: the " +
      "repository statistics, the issues matching the JQL query given in the input, and the activity " +
      "of the #engineering Slack channel. Format them into a digest and email it to the address in " +
      "the input.",
  },
  {
    id: "classify-and-route",
    covers: ["if / else if / else", "condition node", "library function"],
    prompt:
      "Fetch a Jira issue by key and classify its severity. If it is critical, create a follow-up " +
      "issue in the OPS project and send a message to #incidents. If it is high, send a message to " +
      "#engineering. Otherwise just comment nothing and finish by returning the severity.",
  },
  {
    id: "try-catch-finally-audit",
    covers: ["try/catch/finally", "error edge", "narrow try"],
    prompt:
      "Send the release note from the input to the #releases Slack channel. If sending fails, email " +
      "the on-call address in the input with an alert. Either way, always finish by posting one " +
      "audit line to the #audit channel saying whether the release note went out.",
  },
  {
    id: "loop-with-jumps",
    covers: ["for...of", "continue", "break", "counter"],
    prompt:
      "Go through the pull requests opened since the last run for the repository in the input. Skip " +
      "any pull request whose title starts with \"WIP\". For the others, post a comment saying it is " +
      "queued for review. Stop after 5 comments have been posted, even if more pull requests remain.",
  },
];

export interface ChatMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

export interface ModelConfig {
  apiKey: string;
  model: string;
  /**
   * Reasoning models spend the budget on thinking first; too low a cap returns
   * `content: null` with `finish_reason: "length"`. 8k is the floor that made
   * this model answer reliably.
   */
  maxTokens?: number;
  /** Network retries with exponential backoff (429 / 5xx / transport errors). */
  attempts?: number;
  endpoint?: string;
  log?: (message: string) => void;
}

export interface ModelCall {
  content: string;
  finishReason: string | null;
  usage: unknown;
  /** Wall-clock milliseconds of the successful attempt. */
  ms: number;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve();
    }, ms);
  });
}

export async function callModel(messages: ChatMessage[], config: ModelConfig): Promise<ModelCall> {
  const endpoint = config.endpoint ?? "https://openrouter.ai/api/v1/chat/completions";
  const attempts = config.attempts ?? 4;
  const log = config.log ?? ((): void => undefined);
  let lastError = "";

  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    const startedAt = Date.now();
    try {
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${config.apiKey}`,
          "Content-Type": "application/json",
          "HTTP-Referer": "https://github.com/codeflow/codeflow",
          "X-Title": "CodeFlow conformance eval",
        },
        body: JSON.stringify({
          model: config.model,
          max_tokens: config.maxTokens ?? 8000,
          messages,
        }),
      });
      const text = await response.text();
      if (!response.ok) {
        lastError = `HTTP ${String(response.status)}: ${text.slice(0, 300)}`;
        if (response.status === 429 || response.status >= 500) {
          log(`  retrying after ${lastError}`);
          await sleep(2000 * attempt * attempt);
          continue;
        }
        throw new Error(lastError);
      }
      const payload = JSON.parse(text) as {
        choices?: { message?: { content?: string | null }; finish_reason?: string }[];
        usage?: unknown;
        error?: { message?: string };
      };
      if (payload.error !== undefined) {
        lastError = `API error: ${payload.error.message ?? "unknown"}`;
        log(`  retrying after ${lastError}`);
        await sleep(2000 * attempt);
        continue;
      }
      const choice = payload.choices?.[0];
      const content = choice?.message?.content ?? "";
      if (content.trim().length === 0) {
        // Reasoning model with no budget left for an answer — worth retrying once.
        lastError = `empty content (finish_reason=${choice?.finish_reason ?? "?"})`;
        log(`  retrying after ${lastError}`);
        await sleep(1000 * attempt);
        continue;
      }
      return {
        content,
        finishReason: choice?.finish_reason ?? null,
        usage: payload.usage ?? null,
        ms: Date.now() - startedAt,
      };
    } catch (error) {
      lastError = error instanceof Error ? error.message : String(error);
      log(`  transport error: ${lastError}`);
      await sleep(2000 * attempt);
    }
  }

  throw new Error(`model call failed after ${String(attempts)} attempts — ${lastError}`);
}

/**
 * Models wrap code in fences however they were asked not to; that is a prompt
 * artefact, not a conformance defect, so it is stripped before validation.
 */
export function extractFlowSource(content: string): string {
  const fenced = /```(?:ts|typescript|javascript|js)?\s*\n([\s\S]*?)```/.exec(content);
  const source = fenced === null ? content : fenced[1]!;
  return `${source.trim()}\n`;
}

export interface EvalRound {
  round: number;
  source: string;
  level: ConformanceLevel;
  diagnostics: Diagnostic[];
  feedback: string | null;
  finishReason: string | null;
  ms: number;
}

export interface EvalResult {
  intent: string;
  covers: string[];
  firstLevel: ConformanceLevel;
  finalLevel: ConformanceLevel;
  retries: number;
  rounds: EvalRound[];
  error?: string;
}

export interface RunIntentOptions {
  cf: CodeFlowModule;
  intent: EvalIntent;
  config: ModelConfig;
  /** Bounded retry — 10 §5 defaults to 2. */
  maxRetries?: number;
  /** Level the retry loop chases. 10 §5 feeds diagnostics back below L1. */
  target?: "L0" | "L1" | "L2";
  includeExamples?: boolean;
  log?: (message: string) => void;
}

const LEVEL_ORDER: Record<ConformanceLevel, number> = { invalid: 0, L0: 1, L1: 2, L2: 3 };

/** One intent through the whole loop of 10 §5: context → prompt → validate → retry. */
export async function runIntent(options: RunIntentOptions): Promise<EvalResult> {
  const { cf, intent, config } = options;
  const maxRetries = options.maxRetries ?? 2;
  const target = options.target ?? "L1";
  const log = options.log ?? ((): void => undefined);

  const registry = createEvalRegistry(cf);
  const session = cf.createCodeFlow({ registry });
  const context = await session.buildGenerationContext({
    includeExamples: options.includeExamples ?? true,
  });
  const system = cf.renderSystemPrompt(context);

  const messages: ChatMessage[] = [
    { role: "system", content: system },
    { role: "user", content: intent.prompt },
  ];

  const rounds: EvalRound[] = [];
  let retries = 0;

  for (let round = 0; round <= maxRetries; round += 1) {
    log(`  [${intent.id}] round ${String(round)} …`);
    const call = await callModel(messages, config);
    const source = extractFlowSource(call.content);
    const result = await session.validate(source);
    const feedback = cf.renderDiagnosticsFeedback(result, { target });
    rounds.push({
      round,
      source,
      level: result.level,
      diagnostics: result.diagnostics,
      feedback,
      finishReason: call.finishReason,
      ms: call.ms,
    });
    log(`  [${intent.id}] round ${String(round)} → ${result.level} (${String(call.ms)}ms)`);

    if (LEVEL_ORDER[result.level] >= LEVEL_ORDER[target] || feedback === null) break;
    if (round === maxRetries) break;

    retries += 1;
    messages.push({ role: "assistant", content: source });
    messages.push({ role: "user", content: feedback });
  }

  return {
    intent: intent.id,
    covers: intent.covers,
    firstLevel: rounds[0]!.level,
    finalLevel: rounds[rounds.length - 1]!.level,
    retries,
    rounds,
  };
}

export function conformanceRates(results: EvalResult[]): {
  total: number;
  l0: number;
  l1: number;
  l2: number;
} {
  const at = (level: ConformanceLevel): number =>
    results.filter((result) => LEVEL_ORDER[result.finalLevel] >= LEVEL_ORDER[level]).length;
  return { total: results.length, l0: at("L0"), l1: at("L1"), l2: at("L2") };
}
