/**
 * generateToolsDts — 05-registry.md §2.
 *
 * Expected files below are written out and reviewed by hand (11 §3.2: snapshots
 * are reviewed, never blind).
 */

import { describe, expect, it } from "vitest";

import { generateToolsDts } from "../src/codegen/tools-dts.js";
import {
  isGeneratedArtifactStale,
  readGeneratedRegistryHash,
} from "../src/codegen/header.js";
import { createRegistry } from "../src/registry/index.js";
import { createSampleRegistry, HEADER_HASH_LINE } from "./fixtures.js";

function header(hash: string): string {
  return [
    "// Generated by CodeFlow — DO NOT EDIT.",
    "// The registry is the only source of truth; this file is a derived artifact.",
    `// registryHash: ${hash}`,
    "// Regenerate with `codeflow generate`.",
  ].join("\n");
}

describe("tools.d.ts shape", () => {
  it("emits the `Tools` interface the flow contract expects", () => {
    const registry = createSampleRegistry();
    const expected = `${header(registry.registryHash())}

export interface Tools {
  github: {
    /** Get files changed in a PR */
    getFiles(input: { pr: PullRequest }): Promise<File[]>;
    /** Get new pull requests */
    getNewPRs(input: { repo: string }): Promise<PullRequest[]>;
  };
  slack: {
    /** Send a Slack message */
    send(input: { channel: string; message: string }): Promise<void>;
  };
}
`;
    expect(generateToolsDts(registry)).toBe(expected);
  });

  it("emits Promise<void> when a tool declares no output schema", () => {
    const registry = createRegistry();
    registry.registerTool({ name: "slack.send", label: "Send a Slack message", inputSchema: {} });
    expect(generateToolsDts(registry)).toContain("send(input: {}): Promise<void>;");
  });

  it("falls back to the label when there is no description", () => {
    const registry = createRegistry();
    registry.registerTool({ name: "slack.send", label: "Slack Send", inputSchema: {} });
    expect(generateToolsDts(registry)).toContain("/** Slack Send */");
  });

  it("converts a JSON Schema input (the MCP shape) to a TS type", () => {
    const registry = createRegistry();
    registry.registerTool({
      name: "github.getFiles",
      label: "Get PR Files",
      inputSchema: {
        type: "object",
        properties: { pr: { type: "string" }, limit: { type: "integer" } },
        required: ["pr"],
      },
      outputSchema: { type: "array", items: { type: "string" } },
    });
    expect(generateToolsDts(registry)).toContain(
      "getFiles(input: { pr: string; limit?: number }): Promise<string[]>;",
    );
  });

  it("renders a multi-line description as a JSDoc block", () => {
    const registry = createRegistry();
    registry.registerTool({
      name: "slack.send",
      label: "Send",
      description: "Send a Slack message.\nSupports channels and DMs.",
      inputSchema: {},
    });
    expect(generateToolsDts(registry)).toContain(
      ["    /**", "     * Send a Slack message.", "     * Supports channels and DMs.", "     */"].join(
        "\n",
      ),
    );
  });

  it("emits an empty interface for an empty registry (principle 6b)", () => {
    const registry = createRegistry();
    expect(generateToolsDts(registry)).toBe(
      `${header(registry.registryHash())}

// No tools are registered.
export interface Tools {}
`,
    );
  });

  it("is deterministic regardless of registration order", () => {
    const a = createRegistry();
    a.registerTool({ name: "slack.send", label: "Send", inputSchema: {} });
    a.registerTool({ name: "github.getFiles", label: "Files", inputSchema: {} });
    const b = createRegistry();
    b.registerTool({ name: "github.getFiles", label: "Files", inputSchema: {} });
    b.registerTool({ name: "slack.send", label: "Send", inputSchema: {} });
    expect(generateToolsDts(a)).toBe(generateToolsDts(b));
  });

  it("scopes the emitted namespaces when asked (10 §4)", () => {
    const output = generateToolsDts(createSampleRegistry(), { namespaces: ["slack"] });
    expect(output).toContain("slack: {");
    expect(output).not.toContain("github: {");
  });
});

describe("header — stale detection (05 §2)", () => {
  it("carries the registryHash of the registry it was generated from", () => {
    const registry = createSampleRegistry();
    const output = generateToolsDts(registry);
    expect(HEADER_HASH_LINE.exec(output)?.[1]).toBe(registry.registryHash());
    expect(readGeneratedRegistryHash(output)).toBe(registry.registryHash());
  });

  it("reports staleness once the registry changes", () => {
    const registry = createSampleRegistry();
    const output = generateToolsDts(registry);
    expect(isGeneratedArtifactStale(output, registry.registryHash())).toBe(false);

    registry.unregisterTool("slack.send");
    expect(isGeneratedArtifactStale(output, registry.registryHash())).toBe(true);
  });

  it("treats a file with no header hash as stale", () => {
    expect(readGeneratedRegistryHash("export interface Tools {}")).toBeNull();
    expect(isGeneratedArtifactStale("export interface Tools {}", "abc")).toBe(true);
  });
});
