/** generateLibDts — 05-registry.md §2, §4. Expected files reviewed by hand. */

import { describe, expect, it } from "vitest";

import { generateLibDts } from "../src/codegen/lib-dts.js";
import { readGeneratedRegistryHash } from "../src/codegen/header.js";
import { createRegistry } from "../src/registry/index.js";
import { createSampleRegistry } from "./fixtures.js";

function header(hash: string): string {
  return [
    "// Generated by CodeFlow — DO NOT EDIT.",
    "// The registry is the only source of truth; this file is a derived artifact.",
    `// registryHash: ${hash}`,
    "// Regenerate with `codeflow generate`.",
  ].join("\n");
}

describe("lib.d.ts shape", () => {
  it("emits a module declaration for the function library", () => {
    const registry = createSampleRegistry();
    const expected = `${header(registry.registryHash())}

declare module "@flows/lib" {
  /** Is Auth Change */
  export function isAuthChange(files: File[]): boolean;
}
`;
    expect(generateLibDts(registry)).toBe(expected);
  });

  it("maps the named-fields input schema to positional parameters, in key order", () => {
    const registry = createRegistry();
    registry.registerFunction({
      name: "summarize",
      label: "Summarize",
      description: "Summarize the changed files",
      inputSchema: { files: "File[]", limit: "number" },
      outputSchema: "string",
      code: "export function summarize(files: File[], limit: number) { return ''; }",
      modulePath: "@flows/lib",
    });
    expect(generateLibDts(registry)).toContain(
      "export function summarize(files: File[], limit: number): string;",
    );
  });

  it("declares one `args` object for an object-style function", () => {
    // What the function's own source says, so a flow the AI writes against this
    // declaration compiles against the real `lib/` file (05 §4).
    const registry = createRegistry();
    registry.registerFunction({
      name: "imageGen",
      label: "Image Gen",
      argumentStyle: "object",
      inputSchema: { prompt: "string", variants: { type: "number" } },
      outputSchema: "string[]",
      code: "export async function imageGen(args: { prompt: string; variants: number }): Promise<string[]> { return []; }",
      modulePath: "@flows/lib",
    });
    expect(generateLibDts(registry)).toContain(
      "export function imageGen(args: { prompt: string; variants: number }): string[];",
    );
  });

  it("marks an optional field of an object-style function with `?`, not `| undefined`", () => {
    // Nothing shifts when a property is left out, so the widening a positional
    // parameter list needs has nothing to protect here.
    const registry = createRegistry();
    registry.registerFunction({
      name: "imageGen",
      label: "Image Gen",
      argumentStyle: "object",
      inputSchema: {
        type: "object",
        properties: { prompt: { type: "string" }, model: { type: "string" } },
        required: ["prompt"],
      },
      outputSchema: "string[]",
      code: "export async function imageGen(args: { prompt: string; model?: string }): Promise<string[]> { return []; }",
      modulePath: "@flows/lib",
    });
    expect(generateLibDts(registry)).toContain(
      "export function imageGen(args: { prompt: string; model?: string }): string[];",
    );
  });

  it("marks optional JSON Schema properties, widening rather than reordering", () => {
    const registry = createRegistry();
    registry.registerFunction({
      name: "summarize",
      label: "Summarize",
      inputSchema: {
        type: "object",
        properties: { limit: { type: "number" }, files: { type: "array" }, tag: { type: "string" } },
        required: ["files"],
      },
      outputSchema: "string",
      code: "export function summarize() { return ''; }",
      modulePath: "@flows/lib",
    });
    // `limit` is optional but a required parameter follows it, so it is widened
    // to `| undefined` instead of being moved — order is positional.
    expect(generateLibDts(registry)).toContain(
      "export function summarize(limit: number | undefined, files: unknown[], tag?: string): string;",
    );
  });

  it("separates declarations with a blank line and sorts by name", () => {
    const registry = createRegistry();
    for (const name of ["normalize", "isAuthChange"]) {
      registry.registerFunction({
        name,
        label: name,
        inputSchema: { x: "string" },
        outputSchema: "string",
        code: `export function ${name}(x: string) { return x; }`,
        modulePath: "@flows/lib",
      });
    }
    const registryHash = registry.registryHash();
    expect(generateLibDts(registry)).toBe(
      `${header(registryHash)}

declare module "@flows/lib" {
  /** isAuthChange */
  export function isAuthChange(x: string): string;

  /** normalize */
  export function normalize(x: string): string;
}
`,
    );
  });

  it("emits one block per module path, sorted (multi-module is post-MVP)", () => {
    const registry = createRegistry();
    registry.registerFunction({
      name: "get",
      label: "Get",
      inputSchema: { url: "string" },
      outputSchema: "Promise<Response>",
      code: "export function get(url: string) { return fetch(url); }",
      modulePath: "@flows/lib/http",
    });
    registry.registerFunction({
      name: "isAuthChange",
      label: "Is Auth Change",
      inputSchema: { files: "File[]" },
      outputSchema: "boolean",
      code: "export function isAuthChange(files: File[]) { return true; }",
      modulePath: "@flows/lib",
    });
    const output = generateLibDts(registry);
    expect(output.indexOf('declare module "@flows/lib" {')).toBeLessThan(
      output.indexOf('declare module "@flows/lib/http" {'),
    );
  });

  it("says so when the library is empty", () => {
    const registry = createRegistry();
    expect(generateLibDts(registry)).toBe(
      `${header(registry.registryHash())}

// No library functions are registered.
`,
    );
  });

  it("carries the same registryHash as tools.d.ts", () => {
    const registry = createSampleRegistry();
    expect(readGeneratedRegistryHash(generateLibDts(registry))).toBe(registry.registryHash());
  });
});
