/**
 * Generated-artifact header — 05-registry.md §2.
 *
 * Generated files are derived artifacts, never a source. Each carries the
 * `registryHash` of the registry it was generated from, so a mismatch against the
 * current registry surfaces as a `stale-generated-artifacts` diagnostic instead of
 * silently producing a wrong graph.
 */

const HASH_LINE = /^\/\/\s*registryHash:\s*([0-9a-f]+)\s*$/m;

export function generatedHeader(registryHash: string): string {
  return [
    "// Generated by CodeFlow — DO NOT EDIT.",
    "// The registry is the only source of truth; this file is a derived artifact.",
    `// registryHash: ${registryHash}`,
    "// Regenerate with `codeflow generate`.",
  ].join("\n");
}

/** Reads the `registryHash` out of a generated file, or `null` if absent. */
export function readGeneratedRegistryHash(content: string): string | null {
  const match = HASH_LINE.exec(content);
  return match ? match[1]! : null;
}

/** A generated artifact is stale when its header hash differs from the current one. */
export function isGeneratedArtifactStale(content: string, currentRegistryHash: string): boolean {
  return readGeneratedRegistryHash(content) !== currentRegistryHash;
}
