// Generated by CodeFlow — DO NOT EDIT.
// The registry is the only source of truth; this file is a derived artifact.
// registryHash: 34883433168a1db5b8d35e24db133b9844e6dd6b27d17f05db0a237262d6b670
// Regenerate with `codeflow generate`.

export interface Tools {
  filesystem: {
    /** Create a new directory or ensure a directory exists. Can create multiple nested directories in one operation. If the directory already exists, this operation will succeed silently. Perfect for setting up directory structures for projects or ensuring required paths exist. Only works within allowed directories. */
    createDirectory(input: { path: string }): Promise<{ content: string }>;
    /** Get a recursive tree view of files and directories as a JSON structure. Each entry includes 'name', 'type' (file/directory), and 'children' for directories. Files have no children array, while directories always have a children array (which may be empty). The output is formatted with 2-space indentation for readability. Only works within allowed directories. */
    directoryTree(input: { path: string; excludePatterns?: string[] }): Promise<{ content: string }>;
    /** Make line-based edits to a text file. Each edit replaces exact line sequences with new content. Returns a git-style diff showing the changes made. Only works within allowed directories. */
    editFile(input: { path: string; edits: { oldText: string; newText: string }[]; dryRun?: boolean }): Promise<{ content: string }>;
    /** Retrieve detailed metadata about a file or directory. Returns comprehensive information including size, creation time, last modified time, permissions, and type. This tool is perfect for understanding file characteristics without reading the actual content. Only works within allowed directories. */
    getFileInfo(input: { path: string }): Promise<{ content: string }>;
    /** Returns the list of directories that this server is allowed to access. Subdirectories within these allowed directories are also accessible. Use this to understand which directories and their nested paths are available before trying to access files. */
    listAllowedDirectories(input: Record<string, unknown>): Promise<{ content: string }>;
    /** Get a detailed listing of all files and directories in a specified path. Results clearly distinguish between files and directories with [FILE] and [DIR] prefixes. This tool is essential for understanding directory structure and finding specific files within a directory. Only works within allowed directories. */
    listDirectory(input: { path: string }): Promise<{ content: string }>;
    /** Get a detailed listing of all files and directories in a specified path, including sizes. Results clearly distinguish between files and directories with [FILE] and [DIR] prefixes. This tool is useful for understanding directory structure and finding specific files within a directory. Only works within allowed directories. */
    listDirectoryWithSizes(input: { path: string; sortBy?: "name" | "size" }): Promise<{ content: string }>;
    /** Move or rename files and directories. Can move files between directories and rename them in a single operation. If the destination exists, the operation will fail. Works across different directories and can be used for simple renaming within the same directory. Both source and destination must be within allowed directories. */
    moveFile(input: { source: string; destination: string }): Promise<{ content: string }>;
    /** Read the complete contents of a file as text. DEPRECATED: Use read_text_file instead. */
    readFile(input: { path: string; tail?: number; head?: number }): Promise<{ content: string }>;
    /** Read a file and return it as a base64-encoded content block with its MIME type. Image and audio files are returned as image/audio content; any other file type is returned as an embedded resource. Only works within allowed directories. */
    readMediaFile(input: { path: string }): Promise<{ content: ({ type: "image" | "audio"; data: string; mimeType: string } | { type: "resource"; resource: { uri: string; mimeType?: string; blob: string } })[] }>;
    /** Read the contents of multiple files simultaneously. This is more efficient than reading files one by one when you need to analyze or compare multiple files. Each file's content is returned with its path as a reference. Failed reads for individual files won't stop the entire operation. Only works within allowed directories. */
    readMultipleFiles(input: { paths: string[] }): Promise<{ content: string }>;
    /** Read the complete contents of a file from the file system as text. Handles various text encodings and provides detailed error messages if the file cannot be read. Use this tool when you need to examine the contents of a single file. Use the 'head' parameter to read only the first N lines of a file, or the 'tail' parameter to read only the last N lines of a file. Operates on the file as text regardless of extension. Only works within allowed directories. */
    readTextFile(input: { path: string; tail?: number; head?: number }): Promise<{ content: string }>;
    /** Recursively search for files and directories matching a pattern. The patterns should be glob-style patterns that match paths relative to the working directory. Use pattern like '*.ext' to match files in current directory, and '**\/*.ext' to match files in all subdirectories. Returns full paths to all matching items. Great for finding files when you don't know their exact location. Only searches within allowed directories. */
    searchFiles(input: { path: string; pattern: string; excludePatterns?: string[] }): Promise<{ content: string }>;
    /** Create a new file or completely overwrite an existing file with new content. Use with caution as it will overwrite existing files without warning. Handles text content with proper encoding. Only works within allowed directories. */
    writeFile(input: { path: string; content: string }): Promise<{ content: string }>;
  };
}
