// Generated by CodeFlow — DO NOT EDIT.
// The registry is the only source of truth; this file is a derived artifact.
// registryHash: af4672eee47299d4ff53cb89a89e3cd29e5ec504af3eb379b28982b338c6e87c
// Regenerate with `codeflow generate`.

export interface Tools {
  memory: {
    /** Add new observations to existing entities in the knowledge graph */
    addObservations(input: { observations: { entityName: string; contents: string[] }[] }): Promise<{ results: { entityName: string; addedObservations: string[] }[] }>;
    /** Create multiple new entities in the knowledge graph */
    createEntities(input: { entities: { name: string; entityType: string; observations: string[] }[] }): Promise<{ entities: { name: string; entityType: string; observations: string[] }[] }>;
    /** Create multiple new relations between entities in the knowledge graph. Relations should be in active voice */
    createRelations(input: { relations: { from: string; to: string; relationType: string }[] }): Promise<{ relations: { from: string; to: string; relationType: string }[] }>;
    /** Delete multiple entities and their associated relations from the knowledge graph */
    deleteEntities(input: { entityNames: string[] }): Promise<{ success: boolean; message: string }>;
    /** Delete specific observations from entities in the knowledge graph */
    deleteObservations(input: { deletions: { entityName: string; observations: string[] }[] }): Promise<{ success: boolean; message: string }>;
    /** Delete multiple relations from the knowledge graph */
    deleteRelations(input: { relations: { from: string; to: string; relationType: string }[] }): Promise<{ success: boolean; message: string }>;
    /** Open specific nodes in the knowledge graph by their names */
    openNodes(input: { names: string[] }): Promise<{ entities: { name: string; entityType: string; observations: string[] }[]; relations: { from: string; to: string; relationType: string }[] }>;
    /** Read the entire knowledge graph */
    readGraph(input: Record<string, unknown>): Promise<{ entities: { name: string; entityType: string; observations: string[] }[]; relations: { from: string; to: string; relationType: string }[] }>;
    /** Search for nodes in the knowledge graph based on a query */
    searchNodes(input: { query: string }): Promise<{ entities: { name: string; entityType: string; observations: string[] }[]; relations: { from: string; to: string; relationType: string }[] }>;
  };
}
